# Pandas Assignment.

### 1. Create a data series with marks of students : 75, 80, 79, 60

In [1]:
import pandas as pd
import os
marks_series = pd.Series([75,80,79,60])
display(marks_series)
type(marks_series)

name_list = ["Bilal","Danyal","Jamal","Maha"]

0    75
1    80
2    79
3    60
dtype: int64

### 2. Create a data frame with name of students, id and marks

In [2]:
dic = {"name":name_list,"id":[1,2,3,4],"marks":marks_series}
data = pd.DataFrame(dic)
display(data)
type(data)
#data.to_csv("data.csv")

     name  id  marks
0   Bilal   1     75
1  Danyal   2     80
2   Jamal   3     79
3    Maha   4     60

pandas.core.frame.DataFrame

### 3. Now read the file 'data.csv' in panda

In [3]:
os.listdir()
dataframe = pd.read_csv("data for panda exercise.csv")

### 4. What are the columns in the dataframe?

In [4]:
print(dataframe.columns)

Index(['Student Code', 'Degree', 'Student Name', 'Mid', 'Quiz 1', 'Quiz 2',
       'Best of Quizzes', 'Assignment 1', 'Assignment 2',
       'Best of Assignments', 'Total Sessional (50)', 'Final (50)',
       'Total (100)', 'Grade'],
      dtype='object')

### 5. Sort the data based on Marks obtained. Fill all the 'na' cells with 0

In [5]:
a = dataframe.fillna(0)
new_dataframe = a.sort_values(by=["Total (100)"])
display(new_dataframe)

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
15,022-14-19916,BS(CS),Haseeb Sajid,18,0.0,0.0,0,0.0,0.0,0,18,0.0,18,F
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,0.0,2.0,2,8.0,10.0,10,21,8.0,29,F
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,0.0,6,30,9.0,39,F
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,0.0,2.0,2,23,23.0,46,F
1,022-14-110233,BS(CS),Adeel Ahmed,17,0.0,5.0,5,8.0,10.0,10,32,18.0,50,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,0.0,7,34,23.0,57,F
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,0.0,5,8.0,10.0,10,41,21.0,62,C
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,0.0,9,41,22.0,63,C
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,0.0,6,6.0,8.0,8,41,24.0,65,C
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,0.0,10.0,10,38,28.0,66,C
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,0.0,9,43,27.0,70,B
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,0.0,9,40,32.0,72,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,0.0,10,44,29.0,73,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,0.0,9,45,30.0,75,B
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,0.0,5,41,35.0,76,B
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,0.0,9,45,35.0,80,A
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,0.0,8,44,40.0,84,A
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,0.0,8,46,45.0,91,A

### 6. Display the top 10 rows

In [6]:
display(a).head(10)

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
0,022-14-19987,BS(CS),Abdul Basit,28,8.0,3.0,8,7.0,9.0,9,45,25.0,70,B
1,022-14-110233,BS(CS),Adeel Ahmed,17,0.0,5.0,5,8.0,10.0,10,32,18.0,50,F
2,022-14-110585,BS(CS),Afrah Zareen,18,5.0,2.0,5,8.0,10.0,10,33,30.0,63,C
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,0.0,2.0,2,23,23.0,46,F
4,022-14-110648,BS(CS),Ahsan Ali Vohra,27,7.0,6.0,7,7.0,9.0,9,43,34.0,77,B
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
6,022-14-110588,BS(CS),Anas Ali Khan,28,5.0,6.0,6,8.0,10.0,10,44,30.0,74,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
8,022-14-110601,BS(CS),Areesha Sohail,19,9.0,4.0,9,7.0,9.0,9,37,24.0,61,C
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,0.0,8,44,40.0,84,A
10,022-14-110214,BS(CS),Fatima Haider Warsi,30,8.0,7.0,8,8.0,0.0,8,46,45.0,91,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,0.0,5,41,35.0,76,B
12,022-15-110994,BS(CS),Hafiza Tooba Akbani,23,7.0,5.0,7,8.0,10.0,10,40,33.0,73,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
14,022-14-110389,BS(CS),Hareem Afshan,21,7.0,4.0,7,6.0,8.0,8,36,29.0,65,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,0.0,0.0,0,0.0,0.0,0,18,0.0,18,F
16,022-14-110596,BS(CS),Hassam Ahmed,23,5.0,5.0,5,7.0,9.0,9,37,35.0,72,B
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
18,022-14-110223,BS(CS),Madiha Jabeen,16,5.0,2.0,5,8.0,10.0,10,31,29.0,60,C
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
20,022-14-110412,BS(CS),Muhammad Aamir,24,7.0,6.0,7,7.0,9.0,9,40,31.0,71,B
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,0.0,7,34,23.0,57,F
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,0.0,5,8.0,10.0,10,41,21.0,62,C
24,022-14-110215,BS(CS),Muhammad Bilal,28,5.0,4.0,5,9.0,11.0,11,44,33.0,77,B
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
26,022-14-110370,BS(CS),Muhammad Ghazali Faridi,27,6.0,0.0,6,6.0,8.0,8,41,24.0,65,C
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,0.0,6,30,9.0,39,F
30,022-14-110401,BS(CS),Muhammad Shozab,23,8.0,6.0,8,9.0,0.0,9,40,32.0,72,B
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,0.0,10,44,29.0,73,B
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,0.0,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
34,022-14-110413,BS(CS),Nazeer Bin Zafar,25,9.0,6.0,9,8.0,10.0,10,44,42.0,86,A
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,0.0,10.0,10,38,28.0,66,C
36,022-14-110582,BS(CS),Rida Nasim,25,9.0,5.0,9,9.0,0.0,9,43,27.0,70,B
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,0.0,9,45,30.0,75,B
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,0.0,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,0.0,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

AttributeError: 'NoneType' object has no attribute 'head'

### 7. Display the last 10 rows

In [7]:
display(a[-10:])

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
40,022-14-110584,BS(CS),Sharif Taqi,27,9.0,6.0,9,8.0,10.0,10,46,35.0,81,A
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
42,022-14-110587,BS(CS),Sumbul Rehman,28,5.0,6.0,6,8.0,10.0,10,44,23.0,67,C
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
44,022-14-110589,BS(CS),Syed Sohaib,25,7.0,5.0,7,9.0,0.0,9,41,22.0,63,C
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,0.0,9,45,35.0,80,A
46,022-14-19911,BS(CS),Usman Khan,25,8.0,5.0,8,8.0,10.0,10,43,22.0,65,C
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

### 8. Display only the odd rows

In [8]:
display(a[1::2])

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
1,022-14-110233,BS(CS),Adeel Ahmed,17,0.0,5.0,5,8.0,10.0,10,32,18.0,50,F
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,0.0,2.0,2,23,23.0,46,F
5,022-14-110232,BS(CS),Ameer Hamza,25,9.0,6.0,9,8.0,10.0,10,44,27.0,71,B
7,022-14-110388,BS(CS),Aneebullah Niazi,26,9.0,6.0,9,8.0,10.0,10,45,40.0,85,A
9,022-14-110599,BS(CS),Arsalan,28,8.0,6.0,8,8.0,0.0,8,44,40.0,84,A
11,022-14-110591,BS(CS),Habib Ullah,28,8.0,5.0,8,5.0,0.0,5,41,35.0,76,B
13,022-14-110600,BS(CS),Hamza Abdul Jabbar,24,8.0,4.0,8,8.0,10.0,10,42,25.0,67,C
15,022-14-19916,BS(CS),Haseeb Sajid,18,0.0,0.0,0,0.0,0.0,0,18,0.0,18,F
17,022-14-110396,BS(CS),Khalid Anwer,20,8.0,5.0,8,9.0,11.0,11,39,31.0,70,B
19,022-14-110222,BS(CS),Mohammad Hunain,27,9.0,6.0,9,8.0,10.0,10,46,45.0,91,A
21,022-14-110593,BS(CS),Muhammad Abdul Rehman Siddiqui,20,9.0,6.0,9,9.0,11.0,11,40,20.0,60,C
23,022-14-19983,BS(CS),Muhammad Ali Iqbal,26,5.0,0.0,5,8.0,10.0,10,41,21.0,62,C
25,022-14-110105,BS(CS),Muhammad Faraz,26,9.0,6.0,9,8.0,10.0,10,45,41.0,86,A
27,022-14-110452,BS(CS),Muhammad Osama Khan,27,8.0,6.0,8,8.0,10.0,10,45,26.0,71,B
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,0.0,6,30,9.0,39,F
31,022-14-110231,BS(CS),Muhammad Taha Hasnain,27,7.0,5.0,7,10.0,0.0,10,44,29.0,73,B
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
35,022-14-19923,BS(CS),Rabi Ahmed,20,8.0,5.0,8,0.0,10.0,10,38,28.0,66,C
37,022-14-110230,BS(CS),Sadaf Nosheen,27,9.0,5.0,9,9.0,0.0,9,45,30.0,75,B
39,022-14-110107,BS(CS),Sania Iqbal,28,4.0,4.0,4,9.0,11.0,11,43,25.0,68,C
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
43,022-14-110451,BS(CS),Syed Faizan Uddin,28,9.0,4.0,9,6.0,8.0,8,45,34.0,79,B
45,022-14-110400,BS(CS),Syeda Sabika Raza,27,9.0,6.0,9,9.0,0.0,9,45,35.0,80,A
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

### 9. Display only those students who got failed in examination

In [9]:
criteria = a["Grade"] == "F"
display(a[criteria])

,Student Code,Degree,Student Name,Mid,Quiz 1,Quiz 2,Best of Quizzes,Assignment 1,Assignment 2,Best of Assignments,Total Sessional (50),Final (50),Total (100),Grade
1,022-14-110233,BS(CS),Adeel Ahmed,17,0.0,5.0,5,8.0,10.0,10,32,18.0,50,F
3,022-14-19718,BS(CS),Ahmed Ali Raza,14,7.0,2.0,7,0.0,2.0,2,23,23.0,46,F
15,022-14-19916,BS(CS),Haseeb Sajid,18,0.0,0.0,0,0.0,0.0,0,18,0.0,18,F
22,022-14-110398,BS(CS),Muhammad Abdullah,20,7.0,6.0,7,7.0,0.0,7,34,23.0,57,F
28,022-14-110387,BS(CS),Muhammad Saqib Intizar,22,6.0,6.0,6,9.0,11.0,11,39,18.0,57,F
29,022-14-110217,BS(CS),Muhammad Shahroz Khurshid,17,7.0,1.0,7,6.0,0.0,6,30,9.0,39,F
32,022-14-110035,BS(CS),Muhammad Wajahat Khan,9,0.0,2.0,2,8.0,10.0,10,21,8.0,29,F
33,022-14-19919,BS(CS),Muhammad Younus Baig,20,4.0,2.0,4,8.0,10.0,10,34,17.0,51,F
38,022-14-110229,BS(CS),Sadaquat Rafique,9,6.0,6.0,6,5.0,7.0,7,22,17.0,39,F
41,022-14-110225,BS(CS),Shariqa Ahmad,20,7.0,6.0,7,8.0,10.0,10,37,20.0,57,F
47,022-14-110219,BS(CS),Waqar Ahmed,11,9.0,5.0,9,5.0,7.0,7,27,19.0,46,F

### 10. Find out the basic statistical info about data

In [10]:
print("Mean of all Students :",a["Total (100)"].mean())
print("Median of all Students :",a["Total (100)"].median())

Mean of all Students : 66.16666666666667
Median of all Students : 69.0

### 11. How many students got A, B, C, F?

In [11]:
criteria1 = a["Grade"] == "A"
criteria2 = a["Grade"] == "B"
criteria3 = a["Grade"] == "C"
print("Students got A :",a[criteria1].count().mean())
print("Students got B :",a[criteria2].count().mean())
print("Students got C :",a[criteria3].count().mean())
print("Students got F :",a[criteria].count().mean())

Students got A : 8.0
Students got B : 16.0
Students got C : 13.0
Students got F : 11.0

### 12. What are the mean scores for students who got A, B, C, F?

In [12]:
A_Average = a[criteria1]
print("Average(mean) of A : ",A_Average["Total (100)"].mean())
B_Average = a[criteria2]
print("Average(mean) of B : ",B_Average["Total (100)"].mean())
C_Average = a[criteria3]
print("Average(mean) of C : ",C_Average["Total (100)"].mean())
F_Average = a[criteria]
print("Average(mean) of F : ",F_Average["Total (100)"].mean())

Average(mean) of A :  85.5
Average(mean) of B :  73.1875
Average(mean) of C :  64.0
Average(mean) of F :  44.45454545454545